### ISSUE TITLE
Terraform Plan fails with an error

### ISSUE THREAD

**Issue by mahesh-sirikonda** [oracle-quickstart/oci-arch-ci-cd-devops#15]
Step1: Clicked on "Deployed to Oracle Cloud" 
Step2: Filled the necessary details as requested.
Step3: Clicked on Apply
encountered below error:
![image](https://user-images.githubusercontent.com/86659304/161723864-8f8a2fd1-b3d0-4632-bb77-9b8a0a054af9.png)

**Comment by RahulMR42** [comment]
thank you @mahesh-sirikonda for reporting the issues ,we shall check and get 
back to you
