### ISSUE TITLE
"pushcode" resource always assume "main" branch name

### ISSUE THREAD

**Issue by tqumhieh** [oracle-quickstart/oci-arch-ci-cd-devops#7]
"[pushcode](https://github.com/oracle-quickstart/oci-arch-ci-cd-devops/blob/1b90d4f3671338f8716e33233da6cf4871f59808/coderepo.tf#L68)" resource always assume "main" branch name, and this fail if user changed the name of the branch in terraform/ORM variable

**Comment by KartikShrikantHegde** [comment]
issued a fix to solve the issue.
